apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
  namespace: sn-labs-kartik222104
spec:
  workspaces:
    - name: output
    - name: source
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: source

    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: output

    - name: flake8-linting
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: source

    - name: nose-tests
      taskRef:
        name: nose
      workspaces:
        - name: output
          workspace: output
        - name: source
          workspace: source

    - name: buildah-task
      taskRef:
        name: buildah
      workspaces:
        - name: output
          workspace: output
